sugarcube-2:
  macros:
    farmDescShort:
      name: farmDescShort
    resourceBar:
      name: resourceBar
    debug_infoLog:
      name: debug_infoLog
    debug_errorLog:
      name: debug_errorLog
    displayFarmMapSketch:
      name: displayFarmMapSketch
    farm_optionToBuildHouse:
      name: farm_optionToBuildHouse
    morningPhaseContent:
      name: morningPhaseContent
    eveningPhaseContent:
      name: eveningPhaseContent
    morningPhaseActions:
      name: morningPhaseActions
    eveningPhaseActions:
      name: eveningPhaseActions
